server:
  port: 8088
spring:
  application:
    name: campus-secondhand
  # TODO 更改数据库相关资源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/campus-secondhand?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  main:
    banner-mode: off    # 关闭SpringBoot启动图标(banner)
# mybatis-plus日志控制台输出
mybatis-plus:
  type-aliases-package: com.campussecondhand.entity # 别名扫描包
  mapper-locations: "classpath*:/mapper/**/*.xml"
  configuration:
    map-underscore-to-camel-case: false
logging:
  level:
    com.com.campussecondhand: debug
campussecondhand:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: adminkey
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: userkey
    user-ttl: 7200000
    user-token-name: token
